- hosts: web
  sudo: yes
  tasks:	
    - name: clone the source repo
      git: repo=https://github.com/Andrea-Politi/multivac-AP dest=/opt

    - name: build docker image
      docker_image: name="alpine_img" path="/opt/MultiVAC" tag="latest" state="build"

    - name: run container
      docker_container: 
        name: app
        image: alpine_img
        state: started
        network_mode: host
        volumes: /app/logs:/var/log/app
